@echo off
cd /d "%~dp0"
echo Starting Open-Agri OS...
echo Starting Backend Server on Port 5000...
start cmd /k "python frontend/app.py"
echo Waiting for server to start...
timeout /t 5
echo Opening Browser...
start http://localhost:5000
echo Done! You can close this window, but keep the Backend Server window open.
pause
